/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.barebonesim;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class App {

    private static boolean setLookAndFeel(final String arg0) {
        try {
            UIManager.setLookAndFeel(arg0);
            return true;
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        return false;
    }
    
    private static void setLookAndFeel() {
        boolean okay = setLookAndFeel(
            "com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        if (!okay) {
            setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        }
    }

    private static void createAndShowGui() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CustomWindow();
            }
        });
    }

    public static void main(String[] args) {
        setLookAndFeel();
        createAndShowGui();
    }
}
